# Generated by Django 3.0.8 on 2020-07-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_author', models.CharField(default='Anonymous', max_length=20)),
                ('blog_title', models.CharField(default='Blog Title', max_length=50)),
                ('post_date', models.DateField(auto_now=True)),
                ('blog_main', models.CharField(default='', max_length=150)),
                ('head0', models.CharField(default='', max_length=50)),
                ('head0_content', models.CharField(default='', max_length=500)),
                ('head1', models.CharField(default='', max_length=50)),
                ('head1_content', models.CharField(default='', max_length=500)),
                ('head2', models.CharField(default='', max_length=50)),
                ('head2_content', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
