# Generated by Django 3.0.8 on 2020-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200730_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timeStamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
